/** Pre-computed log lines used by the TerminalScene to avoid huge JSX. */
export const feederLines: { ts: string; level: "INFO" | "ERROR"; msg: string }[] = [
  { ts: "09:14:02", level: "INFO", msg: "feeder :: ====== Olist FEEDER (bronze layer) - starting ======" },
  { ts: "09:14:02", level: "INFO", msg: "feeder :: source_dir     = file:///source/olist" },
  { ts: "09:14:02", level: "INFO", msg: "feeder :: raw_base       = hdfs://namenode:9000/data/raw/olist" },
  { ts: "09:14:02", level: "INFO", msg: "feeder :: ingestion_date = 2026-03-22  repartition=4  tables=ALL" },
  { ts: "09:14:08", level: "INFO", msg: "feeder :: Spark application id = app-20260322091408-0001" },
  { ts: "09:14:14", level: "INFO", msg: "feeder :: Table 'customers'  :   99 441 rows  -> /raw/.../year=2026/month=3/day=22" },
  { ts: "09:14:34", level: "INFO", msg: "feeder :: Table 'geolocation': 1 000 163 rows  -> partitioned parquet OK" },
  { ts: "09:14:58", level: "INFO", msg: "feeder :: Table 'order_items':   112 650 rows  -> partitioned parquet OK" },
  { ts: "09:15:09", level: "INFO", msg: "feeder :: Table 'order_payments': 103 886 rows  -> partitioned parquet OK" },
  { ts: "09:15:21", level: "INFO", msg: "feeder :: Table 'order_reviews':  104 719 rows  -> partitioned parquet OK" },
  { ts: "09:15:33", level: "INFO", msg: "feeder :: Table 'orders':         99 441 rows  -> partitioned parquet OK" },
  { ts: "09:15:43", level: "INFO", msg: "feeder :: Table 'products':       32 951 rows  -> partitioned parquet OK" },
  { ts: "09:15:48", level: "INFO", msg: "feeder :: Table 'sellers':         3 095 rows  -> partitioned parquet OK" },
  { ts: "09:15:52", level: "INFO", msg: "feeder :: Table 'category_translation': 71 rows -> partitioned parquet OK" },
  { ts: "09:15:54", level: "INFO", msg: "feeder :: Total rows ingested = 1 556 417  ✓ all tables OK" },
];

export const processorLines: { ts: string; level: "INFO" | "ERROR"; msg: string }[] = [
  { ts: "09:18:41", level: "INFO", msg: "processor :: ====== Olist PROCESSOR (silver layer) - starting ======" },
  { ts: "09:18:50", level: "INFO", msg: "processor :: Spark application id = app-20260322091850-0002" },
  { ts: "09:18:55", level: "INFO", msg: "processor :: Joining orders + items + products + sellers + customers + payments + reviews ..." },
  { ts: "09:19:02", level: "INFO", msg: "processor :: [VALIDATION] input rows = 112 650" },
  { ts: "09:19:04", level: "INFO", msg: "processor :: [VALIDATION] rejected rows = 1 387 (1.23%) - rule 5 timestamp ordering" },
  { ts: "09:19:04", level: "INFO", msg: "processor :: [VALIDATION] surviving rows = 111 263" },
  { ts: "09:19:04", level: "INFO", msg: "processor :: [CACHE] joined_validated persisted (MEMORY_AND_DISK)" },
  { ts: "09:19:04", level: "INFO", msg: "processor :: Applying window functions: row_number, dense_rank, lag" },
  { ts: "09:19:09", level: "INFO", msg: "processor :: [AGG] delivered: 108 665 orders | avg_review=4.13 | revenue=14 502 340.21 BRL" },
  { ts: "09:19:09", level: "INFO", msg: "processor :: [AGG] canceled :     683 orders | avg_review=1.98 | revenue=    85 119.01 BRL" },
  { ts: "09:19:11", level: "INFO", msg: "processor :: [OUTPUT] silver row count = 111 263" },
  { ts: "09:19:23", level: "INFO", msg: "processor :: Writing silver parquet to hdfs://.../silver/olist/orders_enriched" },
  { ts: "09:19:32", level: "INFO", msg: "processor :: Registering Hive table default.silver_orders_enriched" },
  { ts: "09:19:32", level: "INFO", msg: "processor :: ✓ Processor finished OK. 111 263 silver rows produced." },
];
